### ISSUE TITLE
thesis in a standard Linux, please add correct preparation at README

### ISSUE THREAD

**Issue by ppKrauss** [yeslogic/prince-samples#1]
To use `make`  at [thesis](https://github.com/yeslogic/prince-samples/tree/master/thesis) in a standard UBUNTU 14 LTS need a lot of previous installs, 

```
# cd prince-samples/thesis
sudo apt-get update
sudo apt-get install bibtex2html
sudo apt-get install ruby-full   #not need rubygems
sudo gem install sass
make
```

**Comment by ppKrauss** [comment]
**ERROR**  after described procedure, `thesis.css` is empty.

**Comment by PaulBone** [comment]
I have sass 3.4.21, installed via `sudo aptitude install ruby-sass` on Debian stretch  (aptitude has some benefits over apt-get).  This works for me, what version are you using? I can try with that or maybe we can try to fix the .scss file.  Thanks.

**Comment by ppKrauss** [comment]
Hi  @PaulBone, thanks the reply.  After `sudo aptitude install ruby-sass` the problem persist... but now I see that the problem:

*  `sass < thesis.scss > thesis.css`  not works (reported error)...
*  `sass thesis.scss thesis.css`  (or `sass thesis.scss >thesis.css`) works fine!

Ops, and need to remove all to redo correct files...  Let's make (messages):
```
make
bib2bib -q -s editor,author,year < bib.bib > bib-sorted.bib
Sorting...done.
No citation file output (no file name specified)
grep "a class=\"cite" thesis.html | sed -e 's/.*\href=\"#\(.*\)".*/\1/' > citefile.txt
bibtex2html -q -noabstract -nokeywords -dl -nodoc -a -nobibsource \
		-citefile citefile.txt bib-sorted.bib
awk -f make-file.awk < thesis.html > thesis-postproc.html
sass thesis.scss > thesis.css
prince thesis-postproc.html -o thesis.pdf
```
SUGGESTION:   save here at GIT all generated intermediate files (thesis.css, thesis-postproc, etc. except pdf) to avoid  problems for people that not want to install all tools.

**Comment by PaulBone** [comment]
I like your suggestion.  I think that this will make it easier to demonstrate prince, which is the point of these samples.

**Comment by PaulBone** [comment]
Hi @ppKrauss I've committed changes that implement your suggestions and I'll close the issue now.  Please let us know if there's anything else we can help you with. (also feel free to join us on the forums http://www.princexml.com/forum/)
